### ISSUE TITLE
Smooth shutdown?

### ISSUE THREAD

**Issue by Syphurith** [d0k3/Decrypt9#16]
To have a programatically shut down is just the line: `i2cWriteRegister(I2C_DEV_MCU, 0x20, 1 << 0);`
Quite useful sometimes. However due to the current design i felt confused of where to put this line.
Also you would have to bind it with a KEY, and i suggest you to enable this when SD is unmounted.

Also, i don't know if you can let the decryptor wrote a log, so i won't miss those that failed decryption.

**Comment by d0k3** [comment]
That's not an issue, it's a actually two feature requests ;). For the smooth shutdown, look here:
https://github.com/d0k3/Decrypt9/commit/3cfd0feebc0b6f68cdfdf972f77f5f402156d2b3
... and especially read @idgrepthat's comments. We can still discuss this, but I have my doubts about that. Would be pretty useful though.

A log is a great idea! I'll see what I can do.

**Comment by Syphurith** [comment]
@d0k3 It may be able to set up this feature only when the SD is unmounted, so no function related to FS should be in action. I saw his response, however i had to switch to rxTools after decrypt some CIAs with decrypt9, and holding the power to make me a little confused.
The log should be much easy to be implemented, but take care of the FATFS FIL struct, which should cost 4KB or more memory. But for a logger a constant FIL struct should be there before SD unmounted, yes, using append mode.
Those are not issue for sure, however the features/enhancements can be only tracked in such a tab on github.. Well nvm.

**Comment by d0k3** [comment]
The problem with the PowerOff() function seems to be related with the NAND, at least from what I understood. Unmounting the file system before actually exiting is a no brainer, of course.
And yes, the log feature requires a second, constantly open (unless unmounted) FIL struct. 4kB should be in the acceptable range, though. The log function could easily be accessed from the Debug() function, so nothing much else has to be changed.

**Comment by Syphurith** [comment]
@d0k3 Oh. Okey i would remember to just POWER off it then.

**Comment by d0k3** [comment]
One moment... I actually think the PowerOff() would be convenient. I just need to know 100% that it is safe, You may continue the discussion with @idgrepthat here, if you want to: https://github.com/d0k3/Decrypt9/commit/3cfd0feebc0b6f68cdfdf972f77f5f402156d2b3

**Comment by Syphurith** [comment]
@d0k3 Yes i've seen you asking that on 4dsdev. *I seems to be too careful using such thing in rxtools..*

**Comment by d0k3** [comment]
I'm unsure, too. What @plutoo said sounds reasonable, though. Will think about it.

**Comment by Syphurith** [comment]
@d0k3 Thanks. *Eh.. I've built the latest this day however can not get it boot via MSET (4.x DG).*

**Comment by d0k3** [comment]
Can you ask that issue in thread?
http://gbatemp.net/threads/download-decrypt9-wip-3dsx-launcher-dat.388831

I'm not a MSET user myself, however, the latest round of tests for that revealed no problems. Maybe the other users can help you.

**Comment by idgrepthat** [comment]
My concern from the MCU method come from Gw's implementation (if MCU is actually what they use). If you think yours is better and safer, go ahead. I still probably won't use it, heh.

btw, is there any way to use daxtsu's method instead from arm9? seems a lot safer. (if a bit slower)

**Comment by d0k3** [comment]
Reopening this for now...

Daxtsu method uses libctru, to which we don't have access in Decrypt9. It looks safer, though.

**Comment by Syphurith** [comment]
@d0k3 Okey i would go to gbatemp for the help with the MSET.

**Comment by idgrepthat** [comment]
Yes, Daxtsu's method runs in arm11 user mode, while yours is in arm9. Don't you use svcbackdoor + a function pointer arg to issue commands to the arm11 kernel from arm9?

**Comment by Syphurith** [comment]
My MSET boot problem solved, seems i have some files left. After totally cleaned the repo and rebuilt, and updated the Decrypt9WIP folder, that's done and it can be boot via MSET again.

**Comment by d0k3** [comment]
Nope, svcbackdoor is not used in Decrypt9, Would it make sense to port it over?
