### ISSUE TITLE
Missing commit of submodule

### ISSUE THREAD

**Issue by Syphurith** [d0k3/Decrypt9#17]
Mind me please, but sometimes your submodule commit version is removed aggressively that git could not check it out. This may due to force-update/upload-unknown that wiped the commit. I could use the release zip as always, but this may cause some issues when building it. *That's all. Have a good time.*
```
fatal: reference is not a tree: 6b2c7e48c895e37634a9da0a7087da15c2528255
Unable to checkout '6b2c7e48c895e37634a9da0a7087da15c2528255' in submodule path 'BrahmaLoader'
```

**Comment by d0k3** [comment]
I'll see after it, no problem. I did in fact rebase some stuff, so that may be part of the reason.

**Comment by Syphurith** [comment]
@d0k3 No matters, now I've built it with BrahmaLoader master branch. Just a reminder.

**Comment by dark-samus** [comment]
@d0k3 this is happening again, just figured I'd let you know

**Comment by d0k3** [comment]
Should be fixed now. I will never again switch repos for submodules, I swear. This is part of the nightmare the CTRUlib update was :).
