### ISSUE TITLE
De/Encryption will broke game manual which have seed encryption

### ISSUE THREAD

**Issue by sumirecccp** [d0k3/Decrypt9#20]
Hello。
When use D9 to De/Encrypt a 3ds game (CDNto3DS, SDto3DS) with seed encryption, the game manual will cannot be access,or be missing（show the message game card is ejected.） but the game can be played normally.

Or maybe it's the SD Decryption function's bug? I use SD Decryption and Sdto3DS to build the game.

And a game without seed  encryption won't have this bug.

**Comment by dark-samus** [comment]
I believe this is a know thing on gateway (which I assume you're using?) seems to be GWs fault and not D9 or any of it's scripts fault

**Comment by sumirecccp** [comment]
Yes I'm using GW. Is there any method to aviod it? Or which HBL can aviod this problem.

**Comment by dark-samus** [comment]
There is no current way to avoid it afaik

**Comment by d0k3** [comment]
As I said in thread - nag GW until they finally fix it. Or make the problem more known (f.e. with a dedicated thread)  until they have to fix it. I doubt they will do it, though, bunch of lazy b*** they are.
